(()=>{
'use strict';

const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const KEYS={invoices:'bt_invoices_v3',expenses:'bt_expenses_v3',documents:'bt_documents_v3'};
const load=(k,f=[])=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}};
const save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch(e){toast('Browser storage is full. Delete some saved scans or export your records.');return false}};
let invoices=load(KEYS.invoices),expenses=load(KEYS.expenses),documents=load(KEYS.documents);
let draftItems=[{name:'Service',qty:1,price:0,vat:23}],sheetAnalysis=null,scanState=null,toastTimer=null;

const titles={
  dashboard:['Dashboard','Invoices, receipts, documents and business data in one place.'],
  scan:['Scan','Read receipts, invoices and documents from camera photos, images or PDFs.'],
  analyze:['Analyze','Analyze spreadsheets, PDFs and document images.'],
  invoices:['Invoices','Create invoices and track payment status.'],
  money:['Money','Record expenses and monitor profit.'],
  documents:['Documents','Saved document analyses and missing-information checks.']
};

function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function uid(prefix='ID'){return prefix+'-'+Date.now().toString(36).toUpperCase()+'-'+Math.random().toString(36).slice(2,6).toUpperCase()}
function isoToday(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function addDays(dateStr,n){const [y,m,d]=dateStr.split('-').map(Number),x=new Date(Date.UTC(y,m-1,d+n));return x.toISOString().slice(0,10)}
function fmtMoney(n,c='PLN'){return `${Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})} ${c}`}
function download(name,type,data){const blob=data instanceof Blob?data:new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1600)}
function toast(msg){const el=$('#toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3000)}
function go(tab){if(!titles[tab])tab='dashboard';$$('.tab').forEach(x=>x.classList.toggle('active',x.id===tab));$$('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));const [t,s]=titles[tab];$('#pageTitle').textContent=t;$('#pageSubtitle').textContent=s;history.replaceState(null,'','#'+tab);window.scrollTo({top:0,behavior:'smooth'});if(tab==='dashboard')renderDashboard();if(tab==='invoices')renderInvoices();if(tab==='money')renderExpenses();if(tab==='documents')renderDocuments()}
$$('.nav-btn').forEach(b=>b.addEventListener('click',()=>go(b.dataset.tab)));
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));

function invoiceTotals(inv){let net=0,vat=0;(inv.items||[]).forEach(i=>{const base=Math.max(0,Number(i.qty)||0)*Math.max(0,Number(i.price)||0);net+=base;vat+=base*(Math.max(0,Number(i.vat)||0)/100)});return{net,vat,gross:net+vat}}
function dashboardNumbers(){const pln=invoices.filter(i=>(i.currency||'PLN')==='PLN'),revenue=pln.filter(i=>i.status==='paid').reduce((s,i)=>s+invoiceTotals(i).gross,0),outstanding=pln.filter(i=>i.status!=='paid').reduce((s,i)=>s+invoiceTotals(i).gross,0),exp=expenses.reduce((s,e)=>s+Number(e.amount||0),0);return{revenue,outstanding,exp,profit:revenue-exp}}
function renderDashboard(){const n=dashboardNumbers();$('#dashRevenue').textContent=fmtMoney(n.revenue);$('#dashExpenses').textContent=fmtMoney(n.exp);$('#dashProfit').textContent=fmtMoney(n.profit);$('#dashOutstanding').textContent=fmtMoney(n.outstanding);$('#dashProfit').className=n.profit>=0?'positive':'negative';$('#invoiceCount').textContent=`${invoices.length} invoice${invoices.length===1?'':'s'}`;const recent=$('#recentInvoices');recent.innerHTML=invoices.length?invoices.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,5).map(i=>{const t=invoiceTotals(i);return `<div class="list-row"><div><strong>${esc(i.customer)}</strong><span>${esc(i.id)} · ${esc(i.date)}</span></div><div><strong>${fmtMoney(t.gross,i.currency)}</strong><span>${esc(i.status)}</span></div></div>`}).join(''):'<div class="empty-state"><strong>No invoices yet</strong><p>Create your first invoice to start tracking revenue.</p></div>'}

/* ---------- invoices ---------- */
function nextInvoiceNumber(){const year=new Date().getFullYear(),nums=invoices.map(i=>String(i.id||'').match(new RegExp(`^INV-${year}-(\\d+)$`))).filter(Boolean).map(m=>Number(m[1]));return `INV-${year}-${String(Math.max(0,...nums)+1).padStart(3,'0')}`}
function resetInvoiceForm(){draftItems=[{name:'Service',qty:1,price:0,vat:23}];$('#customer').value='';$('#invoiceNumber').value=nextInvoiceNumber();$('#invoiceDate').value=isoToday();$('#invoiceDue').value=addDays(isoToday(),14);$('#invoiceCurrency').value='PLN';$('#invoiceStatus').value='unpaid';renderInvoiceItems()}
function renderInvoiceItems(){const root=$('#invoiceItems');root.innerHTML=draftItems.map((i,idx)=>`<div class="invoice-item" data-index="${idx}"><input aria-label="Item description" data-field="name" value="${esc(i.name)}" placeholder="Description"><input aria-label="Quantity" data-field="qty" type="number" min="0" step="1" value="${Number(i.qty)}"><input aria-label="Price" data-field="price" type="number" min="0" step="0.01" value="${Number(i.price)}"><select aria-label="VAT" data-field="vat"><option value="0" ${Number(i.vat)===0?'selected':''}>VAT 0%</option><option value="5" ${Number(i.vat)===5?'selected':''}>VAT 5%</option><option value="8" ${Number(i.vat)===8?'selected':''}>VAT 8%</option><option value="23" ${Number(i.vat)===23?'selected':''}>VAT 23%</option></select><button type="button" class="remove-item" aria-label="Remove item">×</button></div>`).join('');$$('.invoice-item',root).forEach(row=>{const idx=Number(row.dataset.index);$$('input,select',row).forEach(el=>el.addEventListener('input',()=>{const f=el.dataset.field;draftItems[idx][f]=f==='name'?el.value:Number(el.value||0);updateDraftTotal()}));$('.remove-item',row).addEventListener('click',()=>{if(draftItems.length===1)draftItems[0]={name:'Service',qty:1,price:0,vat:23};else draftItems.splice(idx,1);renderInvoiceItems()})});updateDraftTotal()}
function updateDraftTotal(){$('#invoiceTotal').textContent=fmtMoney(invoiceTotals({items:draftItems}).gross,$('#invoiceCurrency').value||'PLN')}
$('#invoiceCurrency').addEventListener('change',updateDraftTotal);
$('#addItem').addEventListener('click',()=>{draftItems.push({name:'',qty:1,price:0,vat:23});renderInvoiceItems()});
$('#clearInvoice').addEventListener('click',resetInvoiceForm);
$('#newInvoiceBtn').addEventListener('click',()=>{$('#invoiceFormPanel').scrollIntoView({behavior:'smooth'});$('#customer').focus()});
$('#invoiceForm').addEventListener('submit',e=>{e.preventDefault();const customer=$('#customer').value.trim(),id=$('#invoiceNumber').value.trim();if(!customer||!id){toast('Add customer and invoice number.');return}const items=draftItems.filter(i=>String(i.name).trim()&&Number(i.qty)>0);if(!items.length){toast('Add at least one invoice item.');return}if(invoices.some(i=>i.id===id)){toast('That invoice number already exists.');return}invoices.unshift({id,customer,date:$('#invoiceDate').value,due:$('#invoiceDue').value,currency:$('#invoiceCurrency').value,status:$('#invoiceStatus').value,items:items.map(i=>({...i}))});save(KEYS.invoices,invoices);renderInvoices();renderDashboard();resetInvoiceForm();toast('Invoice saved.')});
function setInvoiceStatus(id,status){const inv=invoices.find(i=>i.id===id);if(!inv)return;inv.status=status;save(KEYS.invoices,invoices);renderInvoices();renderDashboard()}
function deleteInvoice(id){if(!confirm('Delete this invoice?'))return;invoices=invoices.filter(i=>i.id!==id);save(KEYS.invoices,invoices);renderInvoices();renderDashboard();resetInvoiceForm();toast('Invoice deleted.')}
function printInvoice(id){const inv=invoices.find(i=>i.id===id);if(!inv)return;const t=invoiceTotals(inv),w=window.open('','_blank','width=820,height=900');if(!w){toast('Allow pop-ups to print the invoice.');return}w.document.write(`<!doctype html><html><head><title>${esc(inv.id)}</title><style>body{font-family:Arial,sans-serif;color:#172033;padding:42px;max-width:850px;margin:auto}h1{font-size:34px;margin:0}header{display:flex;justify-content:space-between;border-bottom:2px solid #172033;padding-bottom:24px;margin-bottom:28px}.meta{line-height:1.7}table{width:100%;border-collapse:collapse;margin-top:28px}th,td{padding:12px;border-bottom:1px solid #ddd;text-align:left}th{background:#f5f6f8}.totals{margin:28px 0 0 auto;width:320px}.totals div{display:flex;justify-content:space-between;padding:8px}.grand{font-size:20px;font-weight:bold;border-top:2px solid #172033}</style></head><body><header><div><h1>INVOICE</h1><small>${esc(inv.id)}</small></div><div class="meta"><b>${esc(inv.customer)}</b><br>Issue: ${esc(inv.date)}<br>Due: ${esc(inv.due)}<br>Status: ${esc(inv.status)}</div></header><table><thead><tr><th>Description</th><th>Qty</th><th>Price</th><th>VAT</th><th>Total</th></tr></thead><tbody>${inv.items.map(i=>{const base=Number(i.qty)*Number(i.price),gross=base*(1+Number(i.vat)/100);return `<tr><td>${esc(i.name)}</td><td>${Number(i.qty)}</td><td>${fmtMoney(i.price,inv.currency)}</td><td>${Number(i.vat)}%</td><td>${fmtMoney(gross,inv.currency)}</td></tr>`}).join('')}</tbody></table><div class="totals"><div><span>Net</span><b>${fmtMoney(t.net,inv.currency)}</b></div><div><span>VAT</span><b>${fmtMoney(t.vat,inv.currency)}</b></div><div class="grand"><span>Total</span><b>${fmtMoney(t.gross,inv.currency)}</b></div></div><script>window.onload=()=>setTimeout(()=>window.print(),250)<\/script></body></html>`);w.document.close()}
function renderInvoices(){const root=$('#invoiceList');root.innerHTML=invoices.length?invoices.map(i=>{const t=invoiceTotals(i);return `<div class="list-row"><div><strong>${esc(i.customer)}</strong><span>${esc(i.id)} · ${esc(i.date)} · due ${esc(i.due)}</span></div><div class="row-actions"><strong>${fmtMoney(t.gross,i.currency)}</strong><select class="status-select" data-status="${esc(i.id)}"><option value="unpaid" ${i.status==='unpaid'?'selected':''}>Unpaid</option><option value="paid" ${i.status==='paid'?'selected':''}>Paid</option><option value="overdue" ${i.status==='overdue'?'selected':''}>Overdue</option></select><button class="mini-btn" data-print="${esc(i.id)}">Print/PDF</button><button class="mini-btn" data-delete="${esc(i.id)}">Delete</button></div></div>`}).join(''):'<div class="empty-state"><strong>No saved invoices</strong><p>Create an invoice above.</p></div>';$$('[data-status]',root).forEach(s=>s.addEventListener('change',()=>setInvoiceStatus(s.dataset.status,s.value)));$$('[data-print]',root).forEach(b=>b.addEventListener('click',()=>printInvoice(b.dataset.print)));$$('[data-delete]',root).forEach(b=>b.addEventListener('click',()=>deleteInvoice(b.dataset.delete)))}

/* ---------- expenses ---------- */
$('#expenseForm').addEventListener('submit',e=>{e.preventDefault();const description=$('#expenseDescription').value.trim(),amount=Number($('#expenseAmount').value);if(!description||!Number.isFinite(amount)||amount<0){toast('Add a valid expense description and amount.');return}expenses.unshift({id:uid('EXP'),description,amount,category:$('#expenseCategory').value,date:$('#expenseDate').value});save(KEYS.expenses,expenses);e.target.reset();$('#expenseDate').value=isoToday();renderExpenses();renderDashboard();toast('Expense added.')});
function deleteExpense(id){if(!confirm('Delete this expense?'))return;expenses=expenses.filter(e=>e.id!==id);save(KEYS.expenses,expenses);renderExpenses();renderDashboard()}
function renderExpenses(){const root=$('#expenseList');$('#expenseCount').textContent=`${expenses.length} record${expenses.length===1?'':'s'}`;root.innerHTML=expenses.length?expenses.map(e=>`<div class="list-row"><div><strong>${esc(e.description)}</strong><span>${esc(e.category)} · ${esc(e.date)}</span></div><div class="row-actions"><strong>${fmtMoney(e.amount)}</strong><button class="mini-btn" data-exp-delete="${esc(e.id)}">Delete</button></div></div>`).join(''):'<div class="empty-state"><strong>No expenses recorded</strong><p>Add your first business expense.</p></div>';$$('[data-exp-delete]',root).forEach(b=>b.addEventListener('click',()=>deleteExpense(b.dataset.expDelete)))}

/* ---------- spreadsheet analysis ---------- */
function parseCsv(text){const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(quoted){if(ch==='"'&&text[i+1]==='"'){field+='"';i++}else if(ch==='"')quoted=false;else field+=ch}else if(ch==='"')quoted=true;else if(ch===','){row.push(field);field=''}else if(ch==='\n'){row.push(field);rows.push(row);row=[];field=''}else if(ch!=='\r')field+=ch}row.push(field);if(row.some(v=>String(v).trim()!==''))rows.push(row);return rows}
function csvCell(v){const s=String(v??'');return /[",\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}
function toCsv(rows){return rows.map(r=>r.map(csvCell).join(',')).join('\r\n')}
function numberValue(v){if(typeof v==='number'&&Number.isFinite(v))return v;let s=String(v??'').trim();if(!s)return NaN;s=s.replace(/\s/g,'').replace(/(?<=\d),(?=\d{1,2}$)/,'.').replace(/[^0-9+\-.]/g,'');const n=Number(s);return Number.isFinite(n)?n:NaN}
function analyzeRows(rows,name){rows=(rows||[]).filter(r=>Array.isArray(r)&&r.some(v=>String(v??'').trim()!==''));if(rows.length<1){toast('The spreadsheet appears to be empty.');return}const width=Math.max(...rows.map(r=>r.length)),headers=Array.from({length:width},(_,i)=>String(rows[0][i]??'').trim()||`Column ${i+1}`),body=rows.slice(1).map(r=>Array.from({length:width},(_,i)=>r[i]??'')).filter(r=>r.some(v=>String(v).trim()!==''));let missing=0;body.forEach(r=>r.forEach(v=>{if(String(v??'').trim()==='')missing++}));const keys=body.map(r=>JSON.stringify(r.map(v=>String(v??'').trim()))),counts=keys.reduce((m,k)=>(m[k]=(m[k]||0)+1,m),{}),duplicates=keys.filter((k,i)=>counts[k]>1&&keys.indexOf(k)!==i).length;const numeric=headers.map((header,i)=>{const present=body.map(r=>r[i]).filter(v=>String(v??'').trim()!=='');const nums=present.map(numberValue).filter(Number.isFinite);if(!present.length||nums.length/present.length<.7)return null;const total=nums.reduce((a,b)=>a+b,0);return{header,count:nums.length,total,average:nums.length?total/nums.length:0,min:nums.length?Math.min(...nums):0,max:nums.length?Math.max(...nums):0}}).filter(Boolean);sheetAnalysis={name,headers,body,missing,duplicates,numeric,keys,counts};renderSheetAnalysis()}
function renderSheetAnalysis(){const a=sheetAnalysis;if(!a)return;$('#analysisEmpty').classList.add('hidden');$('#documentAnalysisPanel').classList.add('hidden');$('#sheetAnalysisPanel').classList.remove('hidden');$('#aRows').textContent=a.body.length;$('#aCols').textContent=a.headers.length;$('#aMissing').textContent=a.missing;$('#aDuplicates').textContent=a.duplicates;$('#aMissing').className=a.missing?'negative':'positive';$('#aDuplicates').className=a.duplicates?'warning':'positive';$('#analysisName').textContent=a.name;$('#analysisMeta').textContent=`${a.body.length} data rows · missing cells are marked red`;$('#numericSummary').innerHTML=a.numeric.length?`<div class="numeric-cards">${a.numeric.map(n=>`<span class="pill"><b>${esc(n.header)}</b> · total ${Number(n.total).toLocaleString(undefined,{maximumFractionDigits:2})} · avg ${Number(n.average).toLocaleString(undefined,{maximumFractionDigits:2})}</span>`).join('')}</div>`:'<p class="info-note">No mostly-numeric columns were detected.</p>';const preview=a.body.slice(0,100);$('#sheetPreview').innerHTML=`<div class="table-wrap"><table><thead><tr>${a.headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${preview.map((r,ri)=>`<tr class="${a.counts[a.keys[ri]]>1?'duplicate-row':''}">${r.map(v=>{const miss=String(v??'').trim()==='';return `<td class="${miss?'missing-cell':''}">${miss?'Missing':esc(v)}</td>`}).join('')}</tr>`).join('')}</tbody></table></div>${a.body.length>100?'<p class="info-note">Showing the first 100 rows.</p>':''}`}
$('#exportCleanCsv').addEventListener('click',()=>{if(!sheetAnalysis)return;const clean=sheetAnalysis.body.map(r=>r.map(v=>typeof v==='string'?v.trim():v)),text=toCsv([sheetAnalysis.headers,...clean]);download((sheetAnalysis.name.replace(/\.[^.]+$/,'')||'cleaned')+'-cleaned.csv','text/csv;charset=utf-8',text)});

/* ---------- OCR + PDF reading ---------- */
function setProgress(prefix,show,percent=0,text=''){const wrap=$(`#${prefix}ProgressWrap`),bar=$(`#${prefix}ProgressBar`),label=$(`#${prefix}ProgressText`);if(!wrap)return;wrap.classList.toggle('hidden',!show);bar.style.width=`${Math.max(0,Math.min(100,percent))}%`;if(text)label.textContent=text}
function isPdf(file){return file&&(/pdf/i.test(file.type)||/\.pdf$/i.test(file.name||''))}
function isSpreadsheet(file){return file&&(/\.(csv|xlsx)$/i.test(file.name||'')||/spreadsheet|csv/i.test(file.type||''))}
async function ocrImage(source,onProgress){if(!window.Tesseract)throw new Error('OCR library did not load. Check your internet connection and try again.');const logger=m=>{if(m.status==='recognizing text'&&onProgress)onProgress(Math.round((m.progress||0)*100),`Reading text… ${Math.round((m.progress||0)*100)}%`)};try{const result=await Tesseract.recognize(source,'eng+pol',{logger});return result.data.text||''}catch(first){const result=await Tesseract.recognize(source,'eng',{logger});return result.data.text||''}}
async function readPdf(file,onProgress){if(!window.pdfjsLib)throw new Error('PDF reader did not load. Refresh and try again.');pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';const data=new Uint8Array(await file.arrayBuffer()),pdf=await pdfjsLib.getDocument({data}).promise;let all='',ocrPages=0;const limit=Math.min(pdf.numPages,12);for(let i=1;i<=limit;i++){const page=await pdf.getPage(i),content=await page.getTextContent(),plain=content.items.map(x=>x.str).join(' ').trim();let pageText=plain;if(pageText.length<25&&ocrPages<3){ocrPages++;const viewport=page.getViewport({scale:1.5}),c=document.createElement('canvas'),ctx=c.getContext('2d');c.width=Math.ceil(viewport.width);c.height=Math.ceil(viewport.height);await page.render({canvasContext:ctx,viewport}).promise;pageText=await ocrImage(c.toDataURL('image/jpeg',.86),(p,t)=>onProgress&&onProgress(Math.round(((i-1)+(p/100))/limit*100),`OCR page ${i}/${limit}: ${t}`))}all+=`\n--- Page ${i} ---\n${pageText}\n`;if(onProgress)onProgress(Math.round(i/limit*100),`Reading PDF page ${i} of ${limit}`)}return{text:all.trim(),pages:pdf.numPages,limited:pdf.numPages>limit}}
function readImageFile(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=()=>reject(new Error('Could not read image.'));r.onload=()=>{const img=new Image();img.onerror=()=>reject(new Error('The selected image could not be opened.'));img.onload=()=>resolve({dataUrl:r.result,img});img.src=r.result};r.readAsDataURL(file)})}
function drawScanImage(){return new Promise((resolve,reject)=>{if(!scanState||!scanState.dataUrl)return resolve();const img=new Image();img.onerror=()=>reject(new Error('Could not render image.'));img.onload=()=>{const c=$('#scanCanvas'),ctx=c.getContext('2d'),rot=((scanState.rotation||0)%360+360)%360,max=1400,baseScale=Math.min(1,max/Math.max(img.width,img.height)),w=Math.max(1,Math.round(img.width*baseScale)),h=Math.max(1,Math.round(img.height*baseScale)),swap=rot===90||rot===270;c.width=swap?h:w;c.height=swap?w:h;ctx.save();ctx.translate(c.width/2,c.height/2);ctx.rotate(rot*Math.PI/180);ctx.filter=scanState.bw?'grayscale(1) contrast(1.28)':'none';ctx.drawImage(img,-w/2,-h/2,w,h);ctx.restore();resolve()};img.src=scanState.dataUrl})}
function thumbnailFromCanvas(){const src=$('#scanCanvas'),c=document.createElement('canvas'),max=420,scale=Math.min(1,max/src.width),w=Math.max(1,Math.round(src.width*scale)),h=Math.max(1,Math.round(src.height*scale));c.width=w;c.height=h;c.getContext('2d').drawImage(src,0,0,w,h);return c.toDataURL('image/jpeg',.68)}

/* ---------- document field extraction ---------- */
function cleanLines(text){return String(text||'').split(/\r?\n/).map(s=>s.replace(/\s+/g,' ').trim()).filter(Boolean)}
function labelValue(lines,labels){for(let i=0;i<lines.length;i++){const low=lines[i].toLowerCase();for(const label of labels){const pos=low.indexOf(label.toLowerCase());if(pos>=0){let value=lines[i].slice(pos+label.length).replace(/^[\s:#\-–—]+/,'').trim();if(value&&value.length>1)return value;if(lines[i+1]&&lines[i+1].length<120)return lines[i+1]}}}return''}
function firstDate(text){const m=String(text||'').match(/\b(?:20\d{2}[-/.]\d{1,2}[-/.]\d{1,2}|\d{1,2}[-/.]\d{1,2}[-/.](?:20)?\d{2})\b/);return m?m[0]:''}
function dateAfter(lines,labels){const v=labelValue(lines,labels),m=v.match(/\b(?:20\d{2}[-/.]\d{1,2}[-/.]\d{1,2}|\d{1,2}[-/.]\d{1,2}[-/.](?:20)?\d{2})\b/);return m?m[0]:''}
function moneyTokens(line){const matches=String(line||'').match(/(?:\d{1,3}(?:[ .]\d{3})*|\d+)[,.]\d{2}\b/g)||[];return matches.map(s=>Number(s.replace(/ /g,'').replace(',','.'))).filter(Number.isFinite)}
function amountAfter(lines,labels){for(const line of lines){const low=line.toLowerCase();if(labels.some(l=>low.includes(l.toLowerCase()))){const nums=moneyTokens(line);if(nums.length)return nums[nums.length-1]}}return null}
function biggestAmount(text){const vals=moneyTokens(text);return vals.length?Math.max(...vals):null}
function currencyFrom(text){const s=String(text||'');if(/\bEUR\b|€/i.test(s))return'EUR';if(/\bUSD\b|\$/i.test(s))return'USD';if(/\bGBP\b|£/i.test(s))return'GBP';if(/\bPLN\b|zł/i.test(s))return'PLN';return''}
function usefulFirstLine(lines){return lines.find(l=>l.length>=2&&l.length<=90&&!/^(invoice|faktura|receipt|paragon|page\s+\d+)/i.test(l))||lines[0]||''}
function field(key,label,value,required=true){return{key,label,value:value===null||value===undefined?'':String(value),required}}
function detectDocumentType(text,hint){if(hint==='invoice'||hint==='receipt')return hint;const s=String(text||'').toLowerCase();if(/\bfaktura\b|\binvoice\b|invoice\s*(no|number)|nr\s*faktury/.test(s))return'invoice';if(/\bparagon\b|\breceipt\b|fiskal|fiscal/.test(s))return'receipt';return'document'}
function analyzeDocumentText(text,hint='auto'){const lines=cleanLines(text),type=detectDocumentType(text,hint);let fields=[];if(type==='invoice'){const invoiceNumber=labelValue(lines,['invoice number','invoice no','invoice #','nr faktury','numer faktury','faktura nr']),seller=labelValue(lines,['seller','sprzedawca','supplier','vendor'])||usefulFirstLine(lines),customer=labelValue(lines,['buyer','nabywca','customer','client','klient','odbiorca']),issueDate=dateAfter(lines,['issue date','date of issue','data wystawienia'])||firstDate(text),dueDate=dateAfter(lines,['due date','payment due','termin płatności','termin platnosci']),net=amountAfter(lines,['net total','netto','net amount']),vat=amountAfter(lines,['vat total','podatek vat','vat amount']),total=amountAfter(lines,['amount due','total due','do zapłaty','do zaplaty','grand total','razem brutto','total','brutto'])??biggestAmount(text),currency=currencyFrom(text),taxId=labelValue(lines,['nip','vat id','tax id']);fields=[field('invoiceNumber','Invoice number',invoiceNumber),field('seller','Seller / supplier',seller),field('customer','Buyer / customer',customer),field('issueDate','Issue date',issueDate),field('dueDate','Due date',dueDate,false),field('net','Net amount',net===null?'':net,false),field('vat','VAT amount',vat===null?'':vat,false),field('total','Total amount',total===null?'':total),field('currency','Currency',currency,false),field('taxId','Tax / VAT ID',taxId,false)]}
else if(type==='receipt'){const seller=usefulFirstLine(lines),date=firstDate(text),total=amountAfter(lines,['total','razem','suma','do zapłaty','do zaplaty','amount'])??biggestAmount(text),receiptNo=labelValue(lines,['receipt no','receipt number','paragon nr','nr paragonu']),vat=amountAfter(lines,['vat','podatek']),payment=labelValue(lines,['payment','płatność','platnosc','method']),currency=currencyFrom(text);fields=[field('seller','Store / seller',seller),field('date','Date',date),field('total','Total amount',total===null?'':total),field('receiptNo','Receipt number',receiptNo,false),field('vat','VAT amount',vat===null?'':vat,false),field('payment','Payment method',payment,false),field('currency','Currency',currency,false)]}
else{const title=usefulFirstLine(lines),date=firstDate(text),reference=labelValue(lines,['reference','ref','document no','document number','numer dokumentu','nr dokumentu']),party=labelValue(lines,['company','firma','name','nazwa','client','customer']);fields=[field('title','Document title / heading',title),field('date','Document date',date),field('reference','Reference / document number',reference,false),field('party','Company / person',party,false)]}
const required=fields.filter(f=>f.required),missing=required.filter(f=>!String(f.value).trim()),completeness=required.length?Math.round((required.length-missing.length)/required.length*100):100;return{docType:type,fields,missing,completeness,text}}
function typeLabel(t){return t==='invoice'?'Invoice':t==='receipt'?'Receipt':'Document'}
function renderFieldChecks(rootId,result){const root=$(rootId);root.innerHTML=result.fields.map(f=>{const miss=f.required&&!String(f.value).trim();return `<div class="field-check ${miss?'missing':''}"><span>${esc(f.label)}${f.required?' *':''}</span><strong>${miss?'Missing':esc(f.value)||'Not detected'}</strong></div>`}).join('')}

/* ---------- scan workflow ---------- */
async function startScan(type,file,inputEl){if(!file)return;scanState={hint:type,name:file.name||`${type}-scan`,isPdf:isPdf(file),dataUrl:null,rotation:0,bw:false,text:'',analysis:null,pages:0};$('#scanWorkspace').classList.remove('hidden');$('#scanCheck').classList.add('hidden');$('#scanName').textContent=scanState.name;$('#scanType').textContent='Preparing scan…';$('#scanBadge').className='scan-badge';$('#scanBadge').textContent='Scanning';$('.pdf-preview').classList.toggle('hidden',!scanState.isPdf);$('#scanCanvas').classList.toggle('hidden',scanState.isPdf);$$('.image-tool').forEach(b=>b.classList.toggle('hidden',scanState.isPdf));setProgress('scan',true,2,'Preparing file…');try{if(scanState.isPdf){const result=await readPdf(file,(p,t)=>setProgress('scan',true,p,t));scanState.text=result.text;scanState.pages=result.pages;$('#pdfPreviewMeta').textContent=`${result.pages} page${result.pages===1?'':'s'}${result.limited?' · first 12 pages analyzed':''}`;await finishScanAnalysis()}else{const image=await readImageFile(file);scanState.dataUrl=image.dataUrl;await drawScanImage();await readCurrentScan()} }catch(err){setProgress('scan',false);$('#scanType').textContent='Could not scan this file';$('#scanBadge').className='scan-badge bad';$('#scanBadge').textContent='Error';toast(err.message||'Could not scan this file.')}finally{if(inputEl)inputEl.value=''}}
async function readCurrentScan(){if(!scanState)return;setProgress('scan',true,5,'Starting OCR…');const source=$('#scanCanvas').toDataURL('image/jpeg',.9);scanState.text=await ocrImage(source,(p,t)=>setProgress('scan',true,p,t));await finishScanAnalysis()}
async function finishScanAnalysis(){scanState.analysis=analyzeDocumentText(scanState.text,scanState.hint);renderFieldChecks('#scanFields',scanState.analysis);$('#scanText').textContent=scanState.text||'No readable text detected.';$('#scanCompleteness').textContent=`${scanState.analysis.completeness}% complete`;$('#scanCheck').classList.remove('hidden');$('#scanType').textContent=`${typeLabel(scanState.analysis.docType)} read · ${scanState.analysis.missing.length} required field${scanState.analysis.missing.length===1?'':'s'} missing`;$('#scanBadge').textContent=scanState.analysis.missing.length?'Needs review':'Complete';$('#scanBadge').className='scan-badge '+(scanState.analysis.missing.length?'bad':'good');setProgress('scan',false)}
$('#receiptCamera').addEventListener('change',e=>startScan('receipt',e.target.files[0],e.target));
$('#receiptInput').addEventListener('change',e=>startScan('receipt',e.target.files[0],e.target));
$('#invoiceCamera').addEventListener('change',e=>startScan('invoice',e.target.files[0],e.target));
$('#invoiceScanInput').addEventListener('change',e=>startScan('invoice',e.target.files[0],e.target));
$('#documentCamera').addEventListener('change',e=>startScan('document',e.target.files[0],e.target));
$('#documentInput').addEventListener('change',e=>startScan('document',e.target.files[0],e.target));
$('#readScan').addEventListener('click',async()=>{if(!scanState)return;if(scanState.isPdf){toast('PDF text has already been read. Choose the PDF again to rescan it.');return}try{await readCurrentScan()}catch(err){setProgress('scan',false);toast(err.message||'OCR failed.')}});
$('#rotateScan').addEventListener('click',async()=>{if(!scanState||scanState.isPdf)return;scanState.rotation=(scanState.rotation+90)%360;await drawScanImage();toast('Rotated. Tap Scan & read text to re-read the rotated page.')});
$('#toggleBW').addEventListener('click',async()=>{if(!scanState||scanState.isPdf)return;scanState.bw=!scanState.bw;await drawScanImage();toast(scanState.bw?'Black & white enhancement on.':'Color view restored.')});
$('#downloadScan').addEventListener('click',()=>{if(!scanState||scanState.isPdf)return;$('#scanCanvas').toBlob(blob=>blob&&download((scanState.name.replace(/\.[^.]+$/,'')||'scan')+'-scan.jpg','image/jpeg',blob),'image/jpeg',.9)});
$('#saveScan').addEventListener('click',()=>{if(!scanState||!scanState.analysis){toast('Scan and read the document first.');return}const thumb=scanState.isPdf?'':thumbnailFromCanvas(),doc={id:uid('DOC'),name:scanState.name,type:scanState.analysis.docType,createdAt:new Date().toISOString(),text:scanState.text,fields:scanState.analysis.fields,missing:scanState.analysis.missing.map(f=>f.label),completeness:scanState.analysis.completeness,thumb,pages:scanState.pages||0};documents.unshift(doc);if(save(KEYS.documents,documents)){renderDocuments();toast('Document analysis saved.')}else documents.shift()});

/* ---------- general Analyze workflow ---------- */
async function analyzeUploadedFile(file){if(!file)return;$('#analysisEmpty').classList.add('hidden');$('#sheetAnalysisPanel').classList.add('hidden');$('#documentAnalysisPanel').classList.add('hidden');setProgress('analysis',true,2,'Opening file…');try{if(isSpreadsheet(file)){let rows;if(/\.csv$/i.test(file.name)||/csv/i.test(file.type)){rows=parseCsv(await file.text())}else{if(!window.XLSX)throw new Error('Excel reader did not load. Refresh and try again.');const wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),sheet=wb.Sheets[wb.SheetNames[0]];rows=XLSX.utils.sheet_to_json(sheet,{header:1,raw:false,defval:''})}analyzeRows(rows,file.name);setProgress('analysis',false)}else{let text='',meta='';if(isPdf(file)){const r=await readPdf(file,(p,t)=>setProgress('analysis',true,p,t));text=r.text;meta=`PDF · ${r.pages} page${r.pages===1?'':'s'}`}else if(/^image\//i.test(file.type)){const image=await readImageFile(file);text=await ocrImage(image.dataUrl,(p,t)=>setProgress('analysis',true,p,t));meta='Image OCR'}else throw new Error('Use CSV, XLSX, PDF, JPG or PNG.');const result=analyzeDocumentText(text,'auto');renderDocumentAnalysis(file.name,result,meta);setProgress('analysis',false)}}catch(err){setProgress('analysis',false);$('#analysisEmpty').classList.remove('hidden');toast(err.message||'Could not analyze this file.')}finally{$('#analysisInput').value=''}}
function renderDocumentAnalysis(name,result,meta){$('#analysisEmpty').classList.add('hidden');$('#sheetAnalysisPanel').classList.add('hidden');$('#documentAnalysisPanel').classList.remove('hidden');$('#docAnalysisName').textContent=name;$('#docAnalysisType').textContent=`${typeLabel(result.docType)} · ${meta||'document text analysis'}`;const score=$('#docAnalysisCompleteness');score.textContent=`${result.completeness}% complete`;score.className='completion-score'+(result.missing.length?' incomplete':'');renderFieldChecks('#docAnalysisFields',result);$('#docAnalysisText').textContent=result.text||'No readable text detected.';const call=$('#docMissingCallout');if(result.missing.length){call.classList.remove('hidden');call.innerHTML=`<strong>Missing information:</strong> ${result.missing.map(f=>esc(f.label)).join(', ')}. Check the original document or enter this information before relying on it.`}else call.classList.add('hidden')}
$('#analysisInput').addEventListener('change',e=>analyzeUploadedFile(e.target.files[0]));

/* ---------- saved documents ---------- */
function deleteDocument(id){if(!confirm('Delete this saved document analysis?'))return;documents=documents.filter(d=>d.id!==id);save(KEYS.documents,documents);renderDocuments();toast('Document deleted.')}
function renderDocuments(){const root=$('#documentGrid');if(!documents.length){root.innerHTML='<div class="empty-state"><strong>No documents saved</strong><p>Scan a receipt, invoice or document and save its analysis.</p></div>';return}root.innerHTML=documents.map(d=>{const miss=(d.missing||[]),thumb=d.thumb?`<img src="${d.thumb}" alt="">`:`<div class="pdf-preview"><strong>${d.pages?'PDF':'DOC'}</strong><span>${d.pages?`${d.pages} page${d.pages===1?'':'s'}`:'Text analysis'}</span></div>`;return `<article class="doc-card ${miss.length?'missing-doc':''}">${thumb}<strong>${esc(d.name)}</strong><span>${esc(typeLabel(d.type))} · ${Number(d.completeness??0)}% complete</span>${miss.length?`<span class="doc-missing">Missing: ${miss.map(esc).join(', ')}</span>`:'<span class="positive">Required information found</span>'}<div class="doc-actions"><button data-doc-delete="${esc(d.id)}">Delete</button></div></article>`}).join('');$$('[data-doc-delete]',root).forEach(b=>b.addEventListener('click',()=>deleteDocument(b.dataset.docDelete)))}

/* ---------- export ---------- */
$('#exportSummary').addEventListener('click',()=>{const n=dashboardNumbers(),rows=[['Business Toolkit summary',new Date().toLocaleString()],['Revenue PLN',n.revenue],['Expenses PLN',n.exp],['Profit PLN',n.profit],['Outstanding PLN',n.outstanding],[],['Invoices',invoices.length],['Expenses',expenses.length],['Saved documents',documents.length],['Documents needing review',documents.filter(d=>(d.missing||[]).length).length]];download('business-toolkit-summary.csv','text/csv;charset=utf-8',toCsv(rows))});

/* ---------- init ---------- */
$('#expenseDate').value=isoToday();
resetInvoiceForm();
renderInvoices();
renderExpenses();
renderDashboard();
renderDocuments();
const start=(location.hash||'#dashboard').slice(1);
go(titles[start]?start:'dashboard');
})();