(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const KEYS={invoices:'bt_invoices_v2',expenses:'bt_expenses_v2',documents:'bt_documents_v2'};
const load=(k,f=[])=>{try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}};
const save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch(e){toast('Browser storage is full. Delete some scans or export your data.');return false}};
let invoices=load(KEYS.invoices), expenses=load(KEYS.expenses), documents=load(KEYS.documents);
let draftItems=[{name:'Service',qty:1,price:0,vat:23}], analysis=null, scanState=null, toastTimer=null;
const titles={dashboard:['Dashboard','Invoices, receipts, documents and business data in one place.'],scan:['Scan','Capture receipts, invoices and documents.'],analyze:['Analyze','Understand CSV and Excel data quickly.'],invoices:['Invoices','Create invoices and track payment status.'],money:['Money','Record expenses and monitor profit.'],documents:['Documents','Your locally stored business scans.']};

function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function uid(prefix='ID'){return prefix+'-'+Date.now().toString(36).toUpperCase()+'-'+Math.random().toString(36).slice(2,6).toUpperCase()}
function isoToday(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function addDays(dateStr,n){const [y,m,d]=dateStr.split('-').map(Number),x=new Date(Date.UTC(y,m-1,d+n));return x.toISOString().slice(0,10)}
function fmtMoney(n,c='PLN'){return `${Number(n||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})} ${c}`}
function download(name,type,data){const blob=data instanceof Blob?data:new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
function go(tab){$$('.tab').forEach(x=>x.classList.toggle('active',x.id===tab));$$('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));const [t,s]=titles[tab]||titles.dashboard;$('#pageTitle').textContent=t;$('#pageSubtitle').textContent=s;history.replaceState(null,'','#'+tab);window.scrollTo({top:0,behavior:'smooth'});if(tab==='dashboard')renderDashboard();if(tab==='invoices')renderInvoices();if(tab==='money')renderExpenses();if(tab==='documents')renderDocuments()}
$$('.nav-btn').forEach(b=>b.addEventListener('click',()=>go(b.dataset.tab)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));

function invoiceTotals(inv){let net=0,vat=0;(inv.items||[]).forEach(i=>{const base=Math.max(0,Number(i.qty)||0)*Math.max(0,Number(i.price)||0);net+=base;vat+=base*(Math.max(0,Number(i.vat)||0)/100)});return{net,vat,gross:net+vat}}
function dashboardNumbers(){const pln=invoices.filter(i=>(i.currency||'PLN')==='PLN'),revenue=pln.filter(i=>i.status==='paid').reduce((s,i)=>s+invoiceTotals(i).gross,0),outstanding=pln.filter(i=>i.status!=='paid').reduce((s,i)=>s+invoiceTotals(i).gross,0),exp=expenses.reduce((s,e)=>s+Number(e.amount||0),0);return{revenue,outstanding,exp,profit:revenue-exp}}
function renderDashboard(){const n=dashboardNumbers();$('#dashRevenue').textContent=fmtMoney(n.revenue);$('#dashExpenses').textContent=fmtMoney(n.exp);$('#dashProfit').textContent=fmtMoney(n.profit);$('#dashOutstanding').textContent=fmtMoney(n.outstanding);$('#dashProfit').className=n.profit>=0?'positive':'negative';$('#invoiceCount').textContent=`${invoices.length} invoice${invoices.length===1?'':'s'}`;const recent=$('#recentInvoices');recent.innerHTML=invoices.length?invoices.slice().sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,5).map(i=>{const t=invoiceTotals(i);return `<div class="list-row"><div><strong>${esc(i.customer)}</strong><span>${esc(i.id)} · ${esc(i.date)}</span></div><div><strong>${fmtMoney(t.gross,i.currency)}</strong><span>${esc(i.status)}</span></div></div>`}).join(''):'<div class="empty-state"><strong>No invoices yet</strong><p>Create your first invoice to start tracking revenue.</p></div>'}

function nextInvoiceNumber(){const year=new Date().getFullYear(),nums=invoices.map(i=>String(i.id||'').match(new RegExp(`^INV-${year}-(\\d+)$`))).filter(Boolean).map(m=>Number(m[1]));return `INV-${year}-${String((Math.max(0,...nums)+1)).padStart(3,'0')}`}
function resetInvoiceForm(){draftItems=[{name:'Service',qty:1,price:0,vat:23}];$('#customer').value='';$('#invoiceNumber').value=nextInvoiceNumber();$('#invoiceDate').value=isoToday();$('#invoiceDue').value=addDays(isoToday(),14);$('#invoiceCurrency').value='PLN';$('#invoiceStatus').value='unpaid';renderInvoiceItems()}
function renderInvoiceItems(){const root=$('#invoiceItems');root.innerHTML=draftItems.map((i,idx)=>`<div class="invoice-item" data-index="${idx}"><input aria-label="Item description" data-field="name" value="${esc(i.name)}" placeholder="Description"><input aria-label="Quantity" data-field="qty" type="number" min="0" step="1" value="${Number(i.qty)}"><input aria-label="Price" data-field="price" type="number" min="0" step="0.01" value="${Number(i.price)}"><select aria-label="VAT" data-field="vat"><option value="0" ${Number(i.vat)===0?'selected':''}>VAT 0%</option><option value="5" ${Number(i.vat)===5?'selected':''}>VAT 5%</option><option value="8" ${Number(i.vat)===8?'selected':''}>VAT 8%</option><option value="23" ${Number(i.vat)===23?'selected':''}>VAT 23%</option></select><button type="button" class="remove-item" aria-label="Remove item">×</button></div>`).join('');$$('.invoice-item',root).forEach(row=>{const idx=Number(row.dataset.index);$$('input,select',row).forEach(el=>el.addEventListener('input',()=>{const f=el.dataset.field;draftItems[idx][f]=f==='name'?el.value:Number(el.value||0);updateDraftTotal()}));$('.remove-item',row).addEventListener('click',()=>{if(draftItems.length===1){draftItems[0]={name:'Service',qty:1,price:0,vat:23}}else draftItems.splice(idx,1);renderInvoiceItems()})});updateDraftTotal()}
function updateDraftTotal(){const total=invoiceTotals({items:draftItems}).gross;$('#invoiceTotal').textContent=fmtMoney(total,$('#invoiceCurrency').value||'PLN')}
$('#invoiceCurrency').addEventListener('change',updateDraftTotal);$('#addItem').addEventListener('click',()=>{draftItems.push({name:'',qty:1,price:0,vat:23});renderInvoiceItems()});$('#clearInvoice').addEventListener('click',resetInvoiceForm);$('#newInvoiceBtn').addEventListener('click',()=>{$('#invoiceFormPanel').scrollIntoView({behavior:'smooth'});$('#customer').focus()});
$('#invoiceForm').addEventListener('submit',e=>{e.preventDefault();const customer=$('#customer').value.trim(),id=$('#invoiceNumber').value.trim();if(!customer||!id){toast('Add customer and invoice number.');return}const items=draftItems.filter(i=>String(i.name).trim()&&Number(i.qty)>0);if(!items.length){toast('Add at least one invoice item.');return}if(invoices.some(i=>i.id===id)){toast('That invoice number already exists.');return}invoices.unshift({id,customer,date:$('#invoiceDate').value,due:$('#invoiceDue').value,currency:$('#invoiceCurrency').value,status:$('#invoiceStatus').value,items:items.map(i=>({...i}))});save(KEYS.invoices,invoices);renderInvoices();renderDashboard();resetInvoiceForm();toast('Invoice saved.')});
function setInvoiceStatus(id,status){const inv=invoices.find(i=>i.id===id);if(!inv)return;inv.status=status;save(KEYS.invoices,invoices);renderInvoices();renderDashboard()}
function deleteInvoice(id){if(!confirm('Delete this invoice?'))return;invoices=invoices.filter(i=>i.id!==id);save(KEYS.invoices,invoices);renderInvoices();renderDashboard();resetInvoiceForm();toast('Invoice deleted.')}
function printInvoice(id){const inv=invoices.find(i=>i.id===id);if(!inv)return;const t=invoiceTotals(inv),w=window.open('','_blank','width=820,height=900');if(!w){toast('Allow pop-ups to print the invoice.');return}w.document.write(`<!doctype html><html><head><title>${esc(inv.id)}</title><style>body{font-family:Arial,sans-serif;color:#172033;padding:42px;max-width:850px;margin:auto}h1{font-size:34px;margin:0}header{display:flex;justify-content:space-between;border-bottom:2px solid #172033;padding-bottom:24px;margin-bottom:28px}.meta{color:#667085;line-height:1.7}table{width:100%;border-collapse:collapse;margin-top:28px}th,td{padding:12px;border-bottom:1px solid #ddd;text-align:left}th{background:#f5f6f8}.totals{margin:28px 0 0 auto;width:320px}.totals div{display:flex;justify-content:space-between;padding:8px}.grand{font-size:20px;font-weight:bold;border-top:2px solid #172033}small{color:#667085}</style></head><body><header><div><h1>INVOICE</h1><small>${esc(inv.id)}</small></div><div class="meta"><b>${esc(inv.customer)}</b><br>Issue: ${esc(inv.date)}<br>Due: ${esc(inv.due)}<br>Status: ${esc(inv.status)}</div></header><table><thead><tr><th>Description</th><th>Qty</th><th>Price</th><th>VAT</th><th>Total</th></tr></thead><tbody>${inv.items.map(i=>{const base=Number(i.qty)*Number(i.price),gross=base*(1+Number(i.vat)/100);return `<tr><td>${esc(i.name)}</td><td>${Number(i.qty)}</td><td>${fmtMoney(i.price,inv.currency)}</td><td>${Number(i.vat)}%</td><td>${fmtMoney(gross,inv.currency)}</td></tr>`}).join('')}</tbody></table><div class="totals"><div><span>Net</span><b>${fmtMoney(t.net,inv.currency)}</b></div><div><span>VAT</span><b>${fmtMoney(t.vat,inv.currency)}</b></div><div class="grand"><span>Total</span><b>${fmtMoney(t.gross,inv.currency)}</b></div></div><script>window.onload=()=>setTimeout(()=>window.print(),250)<\/script></body></html>`);w.document.close()}
function renderInvoices(){const root=$('#invoiceList');root.innerHTML=invoices.length?invoices.map(i=>{const t=invoiceTotals(i);return `<div class="list-row"><div><strong>${esc(i.customer)}</strong><span>${esc(i.id)} · ${esc(i.date)} · due ${esc(i.due)}</span></div><div class="row-actions"><strong>${fmtMoney(t.gross,i.currency)}</strong><select class="status-select" data-status="${esc(i.id)}"><option value="unpaid" ${i.status==='unpaid'?'selected':''}>Unpaid</option><option value="paid" ${i.status==='paid'?'selected':''}>Paid</option><option value="overdue" ${i.status==='overdue'?'selected':''}>Overdue</option></select><button class="mini-btn" data-print="${esc(i.id)}">Print/PDF</button><button class="mini-btn" data-delete="${esc(i.id)}">Delete</button></div></div>`}).join(''):'<div class="empty-state"><strong>No saved invoices</strong><p>Create an invoice above.</p></div>';$$('[data-status]',root).forEach(s=>s.addEventListener('change',()=>setInvoiceStatus(s.dataset.status,s.value)));$$('[data-print]',root).forEach(b=>b.addEventListener('click',()=>printInvoice(b.dataset.print)));$$('[data-delete]',root).forEach(b=>b.addEventListener('click',()=>deleteInvoice(b.dataset.delete)))}

$('#expenseForm').addEventListener('submit',e=>{e.preventDefault();const description=$('#expenseDescription').value.trim(),amount=Number($('#expenseAmount').value);if(!description||!Number.isFinite(amount)||amount<0){toast('Add a valid expense description and amount.');return}expenses.unshift({id:uid('EXP'),description,amount,category:$('#expenseCategory').value,date:$('#expenseDate').value});save(KEYS.expenses,expenses);e.target.reset();$('#expenseDate').value=isoToday();renderExpenses();renderDashboard();toast('Expense added.')});
function deleteExpense(id){if(!confirm('Delete this expense?'))return;expenses=expenses.filter(e=>e.id!==id);save(KEYS.expenses,expenses);renderExpenses();renderDashboard()}
function renderExpenses(){const root=$('#expenseList');$('#expenseCount').textContent=`${expenses.length} record${expenses.length===1?'':'s'}`;root.innerHTML=expenses.length?expenses.map(e=>`<div class="list-row"><div><strong>${esc(e.description)}</strong><span>${esc(e.category)} · ${esc(e.date)}</span></div><div class="row-actions"><strong>${fmtMoney(e.amount)}</strong><button class="mini-btn" data-exp-delete="${esc(e.id)}">Delete</button></div></div>`).join(''):'<div class="empty-state"><strong>No expenses recorded</strong><p>Add your first business expense.</p></div>';$$('[data-exp-delete]',root).forEach(b=>b.addEventListener('click',()=>deleteExpense(b.dataset.expDelete)))}

function parseCsv(text){const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(quoted){if(ch==='"'&&text[i+1]==='"'){field+='"';i++}else if(ch==='"')quoted=false;else field+=ch}else if(ch==='"')quoted=true;else if(ch===','){row.push(field);field=''}else if(ch==='\n'){row.push(field);rows.push(row);row=[];field=''}else if(ch!=='\r')field+=ch}row.push(field);if(row.some(v=>String(v).trim()!==''))rows.push(row);return rows}
function csvCell(v){const s=String(v??'');return /[",\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}
function toCsv(rows){return rows.map(r=>r.map(csvCell).join(',')).join('\r\n')}
function numberValue(v){if(typeof v==='number'&&Number.isFinite(v))return v;let s=String(v??'').trim();if(!s)return NaN;s=s.replace(/\s/g,'').replace(/(?<=\d),(?=\d{1,2}$)/,'.').replace(/[^0-9+\-.]/g,'');const n=Number(s);return Number.isFinite(n)?n:NaN}
function analyzeRows(rows,name){rows=(rows||[]).filter(r=>Array.isArray(r)&&r.some(v=>String(v??'').trim()!==''));if(rows.length<1){toast('The spreadsheet appears to be empty.');return}const width=Math.max(...rows.map(r=>r.length)),headers=Array.from({length:width},(_,i)=>String(rows[0][i]??'').trim()||`Column ${i+1}`),body=rows.slice(1).map(r=>Array.from({length:width},(_,i)=>r[i]??'')).filter(r=>r.some(v=>String(v).trim()!==''));let missing=0;body.forEach(r=>r.forEach(v=>{if(String(v??'').trim()==='')missing++}));const keys=body.map(r=>JSON.stringify(r.map(v=>String(v??'').trim()))),duplicates=keys.length-new Set(keys).size;const numeric=headers.map((header,i)=>{const present=body.map(r=>r[i]).filter(v=>String(v??'').trim()!=='');const nums=present.map(numberValue).filter(Number.isFinite);if(!present.length||nums.length/present.length<.7)return null;const total=nums.reduce((a,b)=>a+b,0);return{header,count:nums.length,total,avg:nums.length?total/nums.length:0}}).filter(Boolean);analysis={name,headers,body,missing,duplicates,numeric};renderAnalysis();toast('Spreadsheet analyzed.')}
$('#sheetInput').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const lower=file.name.toLowerCase();if(lower.endsWith('.csv'))analyzeRows(parseCsv(await file.text()),file.name);else if(lower.endsWith('.xlsx')){if(!window.XLSX)throw new Error('Excel reader did not load. Check internet connection or use CSV.');const data=await file.arrayBuffer(),wb=XLSX.read(data,{type:'array'}),sheet=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(sheet,{header:1,defval:'',raw:false});analyzeRows(rows,file.name)}else throw new Error('Please upload a .csv or .xlsx file.')}catch(err){console.error(err);toast(err.message||'Could not analyze that file.')}finally{e.target.value=''}});
function renderAnalysis(){if(!analysis)return;$('#analysisEmpty').classList.add('hidden');$('#analysisPanel').classList.remove('hidden');$('#aRows').textContent=analysis.body.length;$('#aCols').textContent=analysis.headers.length;$('#aMissing').textContent=analysis.missing;$('#aDuplicates').textContent=analysis.duplicates;$('#analysisName').textContent=analysis.name;$('#analysisMeta').innerHTML=`<span class="pill">${analysis.body.length} data rows</span><span class="pill">${analysis.headers.length} columns</span>`;$('#numericSummary').innerHTML=analysis.numeric.length?`<div class="table-wrap"><table><thead><tr><th>Numeric column</th><th>Values</th><th>Total</th><th>Average</th></tr></thead><tbody>${analysis.numeric.slice(0,12).map(n=>`<tr><td>${esc(n.header)}</td><td>${n.count}</td><td>${Number(n.total).toLocaleString()}</td><td>${Number(n.avg).toLocaleString(undefined,{maximumFractionDigits:2})}</td></tr>`).join('')}</tbody></table></div>`:'<div class="info-note">No strongly numeric columns were detected.</div>';$('#sheetPreview').innerHTML=`<div class="table-wrap"><table><thead><tr>${analysis.headers.slice(0,8).map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${analysis.body.slice(0,10).map(r=>`<tr>${analysis.headers.slice(0,8).map((_,i)=>`<td>${esc(r[i])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
$('#exportCleanCsv').addEventListener('click',()=>{if(!analysis)return;const seen=new Set(),unique=[];analysis.body.forEach(r=>{const k=JSON.stringify(r.map(v=>String(v??'').trim()));if(!seen.has(k)){seen.add(k);unique.push(r)}});const base=analysis.name.replace(/\.[^.]+$/,'');download(`cleaned-${base}.csv`,'text/csv;charset=utf-8','\ufeff'+toCsv([analysis.headers,...unique]));toast('Cleaned CSV downloaded.')});

function resizeImage(img,maxW=1200,maxH=1600){let w=img.naturalWidth,h=img.naturalHeight,scale=Math.min(1,maxW/w,maxH/h);return{w:Math.round(w*scale),h:Math.round(h*scale)}}
function loadScan(file,type){if(!file||!file.type.startsWith('image/')){toast('Choose an image file.');return}const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const {w,h}=resizeImage(img),canvas=$('#scanCanvas'),ctx=canvas.getContext('2d');canvas.width=w;canvas.height=h;ctx.drawImage(img,0,0,w,h);scanState={type,name:file.name||`${type}-${Date.now()}.jpg`,bw:false,base:canvas.toDataURL('image/jpeg',.78)};$('#scanWorkspace').classList.remove('hidden');$('#scanName').textContent=file.name||'Captured document';$('#scanType').textContent=type[0].toUpperCase()+type.slice(1);$('#scanWorkspace').scrollIntoView({behavior:'smooth',block:'start'})};img.src=reader.result};reader.readAsDataURL(file)}
[['#receiptInput','receipt'],['#invoiceScanInput','invoice'],['#documentInput','document']].forEach(([sel,type])=>$(sel).addEventListener('change',e=>{loadScan(e.target.files[0],type);e.target.value=''}));
function currentCanvasUrl(){return $('#scanCanvas').toDataURL('image/jpeg',.76)}
function restoreBase(){if(!scanState)return;const img=new Image();img.onload=()=>{const c=$('#scanCanvas'),ctx=c.getContext('2d');c.width=img.width;c.height=img.height;ctx.drawImage(img,0,0)};img.src=scanState.base}
$('#rotateScan').addEventListener('click',()=>{if(!scanState)return;const c=$('#scanCanvas'),tmp=document.createElement('canvas');tmp.width=c.height;tmp.height=c.width;const ctx=tmp.getContext('2d');ctx.translate(tmp.width/2,tmp.height/2);ctx.rotate(Math.PI/2);ctx.drawImage(c,-c.width/2,-c.height/2);c.width=tmp.width;c.height=tmp.height;c.getContext('2d').drawImage(tmp,0,0);scanState.base=currentCanvasUrl();scanState.bw=false});
$('#toggleBW').addEventListener('click',()=>{if(!scanState)return;if(scanState.bw){scanState.bw=false;restoreBase();return}const c=$('#scanCanvas'),ctx=c.getContext('2d'),data=ctx.getImageData(0,0,c.width,c.height),d=data.data;for(let i=0;i<d.length;i+=4){const g=0.299*d[i]+0.587*d[i+1]+0.114*d[i+2],v=g>165?255:g<75?0:g;d[i]=d[i+1]=d[i+2]=v}ctx.putImageData(data,0,0);scanState.bw=true});
$('#downloadScan').addEventListener('click',()=>{if(!scanState)return;const a=document.createElement('a');a.href=currentCanvasUrl();a.download=(scanState.name.replace(/\.[^.]+$/,'')||'scan')+'-scan.jpg';a.click()});
$('#saveScan').addEventListener('click',()=>{if(!scanState)return;const url=currentCanvasUrl(),doc={id:uid('DOC'),type:scanState.type,name:scanState.name,date:isoToday(),image:url};documents.unshift(doc);if(save(KEYS.documents,documents)){renderDocuments();renderDashboard();toast('Document saved locally.')}});
function deleteDocument(id){if(!confirm('Delete this saved document?'))return;documents=documents.filter(d=>d.id!==id);save(KEYS.documents,documents);renderDocuments();toast('Document deleted.')}
function renderDocuments(){const root=$('#documentGrid');root.innerHTML=documents.length?documents.map(d=>`<article class="doc-card"><img src="${d.image}" alt="${esc(d.type)} scan preview"><strong>${esc(d.name)}</strong><span>${esc(d.type)} · ${esc(d.date)}</span><div class="doc-actions"><a href="${d.image}" download="${esc((d.name||'scan').replace(/\.[^.]+$/,'')+'-scan.jpg')}">Download</a><button data-doc-delete="${esc(d.id)}">Delete</button></div></article>`).join(''):'<div class="empty-state"><span>▱</span><strong>No saved documents</strong><p>Use Scan to capture a receipt, invoice or document.</p></div>';$$('[data-doc-delete]',root).forEach(b=>b.addEventListener('click',()=>deleteDocument(b.dataset.docDelete)))}

$('#exportSummary').addEventListener('click',()=>{const n=dashboardNumbers(),rows=[['Business Toolkit summary',''],['Generated',new Date().toLocaleString()],['Revenue (PLN paid invoices)',n.revenue.toFixed(2)],['Expenses (PLN)',n.exp.toFixed(2)],['Profit (PLN)',n.profit.toFixed(2)],['Outstanding (PLN)',n.outstanding.toFixed(2)],['Invoices',invoices.length],['Expenses records',expenses.length],['Saved documents',documents.length],['Note','Non-PLN invoice totals are not converted into the PLN dashboard.']];download('business-summary.csv','text/csv;charset=utf-8','\ufeff'+toCsv(rows));toast('Business summary downloaded.')});

$('#expenseDate').value=isoToday();resetInvoiceForm();renderInvoices();renderExpenses();renderDocuments();renderDashboard();const initial=location.hash.slice(1);if(titles[initial])go(initial);
})();
